### ISSUE TITLE
Exception while processing metrics issue

### ISSUE THREAD

**Issue by mancmanomyst** [pivotalsoftware/newrelic_pivotal_agent#8]
Hi Guys,

I'm trialling out New Relic and your plugin for monitoring RabbitMQ queues.

My environment is:
- Windows Server 2008 R2 x64 virtual machine
- Ruby 2.0.0p195 with DevKit-mingw64-64-4.7.2-20130224-1432 Dev Kit
- RabbitMQ Server 3.1.3 with the rabbitmqadmin plugin

RabbitMQ is running and I can connect to it fine from http://localhost:15672/ using the default credentials (guest guest).

I've followed the readme to install the plugin and all was good through the installation. My newrelic)plugin.yml looks like this (comments emitted)

```
newrelic:
  license_key: '80b33bac3033e1b7a8ce7500653d4225b976d86c'
  verbose: 1
agents:
  rabbitmq:
    management_api_url: http://guest:guest@localhost:15672
```

Any ideas what could be causing the Exception while processing metrics. Check configuration message to display?
